//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    pub macro_id: i64,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    #[sea_orm(
        belongs_to,
        from = "macro_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub melmacro: HasOne<super::melmacro::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
