//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "macro_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    pub owner_id: i64,

    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub owner: HasOne<super::owner::Entity>,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    pub is_subscribable: bool,

    #[sea_orm(has_many)]
    pub macros: HasMany<super::melmacro::Entity>,

    #[sea_orm(has_many, via = "subscription", relation_enum = "Subscriber")]
    pub subscribers: HasMany<super::owner::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
