//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "macro")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    pub group_id: i64,

    pub creator_id: i64,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    #[sea_orm(column_type = "Text")]
    pub contents: String,

    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub group: HasOne<super::macro_group::Entity>,

    #[sea_orm(
        belongs_to,
        from = "creator_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub owner: HasOne<super::owner::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
