//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "name_fts")]
pub struct Model {
    pub name: Option<String>,
    pub macro_id: Option<String>,
    pub alias_id: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
