//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "owners")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    pub is_server: bool,

    #[sea_orm(has_many)]
    pub created_macros: HasMany<super::macros::Entity>,

    #[sea_orm(has_many, via = "subscriptions")]
    pub subscriptions: HasMany<super::macro_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
