//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::macro_group as MacroGroup;
pub use super::melmacro as Macro;
pub use super::owner as Owner;
pub use super::subscription as Subscription;
pub use super::alias as Alias;
