//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::macro_group::Entity as MacroGroups;
pub use super::melmacro::Entity as Macros;
pub use super::owner::Entity as Owners;
pub use super::subscription::Entity as Subscriptions;
