//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subscription")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub subscriber_id: i64,
    
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: i64,
    
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub macro_groups: HasOne<super::macro_group::Entity>,
    
    #[sea_orm(
        belongs_to,
        from = "subscriber_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub owners: HasOne<super::owner::Entity>,
    
}

impl ActiveModelBehavior for ActiveModel {}
